name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: "5.5"
          AUTO_PUSH: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
